### ISSUE TITLE
Bug: inputs don't get validated on enter/return key

### ISSUE THREAD

**Issue by kaatt** [ffxsam/formous#14]
Bug:

1. Make a normal form like:

```
<form onSubmit={formSubmit(this.handleSubmit)}>
    <input type="text" placeholder="username" value={username.value} {...username.events} />
    <input type="password" placeholder="password" value={password.value} {...password.events} />
    <button type="submit">Submit</button>
</form>
```

2. User clicks the `username` input.
3. Types the username
4. Presses <kbd>Tab</kbd>
5. `password` input gets focus
6. Types any valid password
7. Presses Enter.
8. Guess what they see? `formStatus.valid` is `false` even when the inputs are correct so `handleSubmit` alerts `Please address the errors in the form`
9. User clicks the button. Works fine because password input loses focus and gets validated.

Possible Fixes:
1. Give users a way to manually validate the form anytime they want to.
2. Validate the form before invoking the callback passed to `formSubmit`.

Probably would fix #7

**Comment by ffxsam** [comment]
Yep, this is a known issue. I'll get to this soon.

**Comment by rmurthi** [comment]
Also face this bug :(.
