### ISSUE TITLE
Doesn't support IE 9-11

### ISSUE THREAD

**Issue by kaatt** [ffxsam/formous#16]
` Object doesn't support property or method 'findIndex'`

**Comment by ffxsam** [comment]
Fixed in the latest release

**Comment by kaatt** [comment]
Thanks. I'm using webpack and uglify. Shouldn't that code be automatically removed because it's related to the tests or am I misunderstanding something?

**Comment by ffxsam** [comment]
Not those kinds of tests. The code in `dx.js` is "developer experience" related, which just provides a bunch of checks to make sure that a developer is using Formous properly. And it's checking to make sure the Formous tests are listed in the correct order (non-critical always after critical tests).

**Comment by kaatt** [comment]
Should use `NODE_ENV !== production` for that probably?

I just checked, the latest update increased my webpack bundle size (after uglify) about ~80 KB. I'm guessing the complete lodash is getting included.

**Comment by ffxsam** [comment]
>Should use NODE_ENV !== production for that probably?

Ah, yes! Very good point. I'll add it when I get time, or you're welcome to do a PR.

>I just checked, the latest update increased my webpack bundle size (after uglify) about ~80 KB. I'm guessing the complete lodash is getting included.

Another good point. I see you just did a PR for this, I'll check it out.

**Comment by kaatt** [comment]
I'll check what they do in other libraries and try to make a PR.

Do you dogfood this library?

**Comment by ffxsam** [comment]
Yep, all my repos are dogfooded. :) I usually build them out of a need I have, and then release it publicly.

BTW, I would try to limit the amount of PRs for now. I have a big code health update planned when I have time, which will probably change 20-25% of the codebase. At some point I'll also add support for dropdowns and radio buttons as well.

**Comment by kaatt** [comment]
Great, hope to see something for #14 soon
