### ISSUE TITLE
Suggestion on package name

### ISSUE THREAD

**Issue by mauriciosoares** [ffxsam/formous#5]
Hey! nice work on formous... I always get hipped with high order components :D

I'd like to suggest you to rename your package to `react-formous`, considering that all packages strictly created for react has this prefix... this would make it easier for react developers to find your package (at least it would for me).

Also, the name is available for registration :D https://www.npmjs.com/package/react-formous

This is just a suggestion though, `formous` is still a great name

:+1:

**Comment by ffxsam** [comment]
I had thought about that. But then I thought "hey, Radium" has a cool single name with no prefixes. 😁  I might consider it. Is it possible to change a package name without messing people up who are already using it?

**Comment by mauriciosoares** [comment]
totally, formous is a great name...

About changing the name, I don't think that's possible... but you can deprecate this package, and warn people in your repository to start using the "new" one...

https://docs.npmjs.com/cli/deprecate

probably not a good idea if your package has been downloaded several times... otherwise it would be something to consider :)

I'm closing this issue, as you have thought about it already.

Cheers!
