### ISSUE TITLE
Usage of HOC

### ISSUE THREAD

**Issue by Andarist** [ffxsam/formous#9]
Just wondering if usage of HOC is right here. Shouldnt this technique be used for extending component behaviour but without it knowing it? 

Here we have used it to inject few things into it. Seems for me that regular component with children would be more appropriate here. What are your thoughts on the matter?

Cheers.

**Comment by ffxsam** [comment]
Well, it certainly passes my first rule: if it works, it works! ;) But as far as HOC best practices (if there is such a thing), I think this is acceptable. There's no _direct_ communication between the two components, but the HOC is returning props to be applied to the component, based on the options passed into Formous. Generally, the attitude of an HOC toward the wrapped component is: “I don't want to know anything about your structure, just give me some options and I'll give back some props.”

I did think about having Formous acting as a parent component that injects props into its children. Though it gets tricky when people start burying the input fields deeply inside of other components, and I also didn't want to restrict where people could use the error props in the hierarchy of their component's markup (in case they wanted the error props outside `<Formous>`.
